### PR TITLE
Ignore whole .idea directory

### PR DESCRIPTION
**Pull request by marcin-kozinski**
Upon importing a freshly cloned repo Android Studio creates a bunch of config files in .idea directory. For me there was one because I clicked on the suggestion to add a VCS root. Another because I fixed the run configuration (by default it tries to launch an activity, but there is none here, so the default run config was not functional). There's a bunch more of them that just spawned automatically without any action on my part.

I am assuming there is no intention to sync this configuration between clones, seeing as it isn't provided in the repository. I agree with this choice and with this change suggest to simply ignore the whole .idea directory and let each Android Studio instance generate it's own config files.

### CODE REVIEW

**Comment by nickbutcher** [comment]
Thanks for your pull request. It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://cla.developers.google.com/ to sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits.
If you signed the CLA as a corporation, please let us know the company's name.

**Comment by jaredsburrows** [comment]
@nickbutcher This is on your github account. Why are you asking to sign a CLA?

**Comment by nickbutcher** [comment]
Because all of the code is copyright Google.

**Comment by marcin-kozinski** [comment]
Hi Nick! Thanks for an awesome project and for all the hard work you're doing for the Android community!

I understand it's not your choice, all this about CLAs and copyright... Do you want to maybe update gitignore yourself if you think it makes sense and close this PR? I for one wouldn't mind.

Cheers and all the best!

**Comment by nickbutcher** [comment]
Ok then. Fixed in 94f3ec064b2feac3c268c399d4aaa99cc9979b2b.

**Comment by marcin-kozinski** [comment]
Thanks, Nick! 👍

**Pull request closed without merging**
